version: '2'

services:

  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - 9999:80
    volumes:
      - ./src/mynews/mynews:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /src

  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./src/mynews/mynews:/src
      - ./php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /src

  mysql:
    image: mysql
    container_name: "laravel-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
